### ISSUE TITLE
reflectutil -- support ppc64le arch

### ISSUE THREAD

**Issue by mallochine** [camlistore/go4#29]
Hi. I was wondering if anybody could do the ppc64le versions of reflectutil/*.s files? Thanks...

FYI, this was the compile error I got:

```
# go4.org/reflectutil
go/src/go4.org/reflectutil/asm_b.s:13: unrecognized instruction "B"
go/src/go4.org/reflectutil/asm_b.s:17: unrecognized instruction "B"
asm: assembly of go/src/go4.org/reflectutil/asm_b.s failed
```

**Comment by shurcooL** [comment]
As a workaround, you should be able to use the "safe" implementation:

https://github.com/camlistore/go4/blob/master/reflectutil/swapper_safe.go

You'd just need to modify the build tags so that it picks up ppc64le too.

Of course, I would imagine it's not as fast as the assembly implementations, so a ppc64le-specific fix is likely a better solution.

**Comment by bradfitz** [comment]
I'm fine with slow for now. We should add +build go1.8 tags to use the native Swapper. Then ppc64le would only be slow on go1.7 and below.

**Comment by mpl** [comment]
https://review.gerrithub.io/#/c/362438/

**Comment by mallochine** [comment]
thanks guys!
